# Generated by Django 3.2.16 on 2023-05-04 09:21

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('tendelapp', '0002_auto_20230504_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('main_address', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('manager_name', models.CharField(max_length=100)),
                ('manager_contact', models.CharField(max_length=100)),
                ('manager_email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['-branch_id'],
            },
        ),
    ]
