# Generated by Django 3.2.16 on 2023-05-04 10:41

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('tendelapp', '0004_alter_branch_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
