# Generated by Django 3.2.16 on 2023-05-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendelapp', '0006_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('gallery_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='default.jpg', upload_to='gallery/')),
            ],
            options={
                'ordering': ['-gallery_id'],
            },
        ),
    ]
