# Generated by Django 3.2.16 on 2023-05-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendelapp', '0010_alter_branch_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='map_link',
            field=models.URLField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3534.894187449424!2d85.5231652!3d27.6277936!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39eb09c614ab615f%3A0x6af270ba59691ae8!2sTENDEL%20Hardware%20Pvt.Ltd!5e0!3m2!1sen!2snp!4v1683780410036!5m2!1sen!2snp', max_length=500),
        ),
    ]
