# Generated by Django 3.2.16 on 2023-05-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendelapp', '0011_alter_branch_map_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('discount', models.CharField(max_length=100)),
                ('validtime', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-offer_id'],
            },
        ),
        migrations.AlterField(
            model_name='branch',
            name='map_link',
            field=models.URLField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3535.025576022263!2d85.52134197479813!3d27.623724529175934!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39eb09f4da6ff8e9%3A0x682749aefd222d53!2sTendel%20Hardware%20Pvt.%20Ltd.!5e0!3m2!1sen!2snp!4v1683803037596!5m2!1sen!2snp', max_length=500),
        ),
    ]
