# Generated by Django 3.2.19 on 2023-05-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendelapp', '0012_auto_20230512_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='team/')),
            ],
            options={
                'ordering': ['-team_id'],
            },
        ),
    ]
