# Generated by Django 3.2.16 on 2023-05-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendelapp', '0013_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='views',
        ),
        migrations.AlterField(
            model_name='branch',
            name='map_link',
            field=models.URLField(default=' https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3534.894034741719!2d85.52059027426827!3d27.62779832899771!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39eb09c614ab615f%3A0x6af270ba59691ae8!2sTENDEL%20Hardware%20Pvt.Ltd!5e0!3m2!1sen!2snp!4v1684647619175!5m2!1sen!2snp ', max_length=500),
        ),
        migrations.DeleteModel(
            name='IpModel',
        ),
    ]
