# Generated by Django 3.2.16 on 2023-05-31 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendelapp', '0014_auto_20230530_1014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
