# Generated by Django 3.2.16 on 2023-05-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendelapp', '0016_homeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
                ('display_modal', models.BooleanField(default=True)),
            ],
        ),
    ]
