# Generated by Django 3.2.16 on 2023-05-31 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendelapp', '0017_modal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modal',
            name='display_modal',
        ),
    ]
