# Generated by Django 3.2.19 on 2023-05-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendelapp', '0018_remove_modal_display_modal'),
    ]

    operations = [
        migrations.AddField(
            model_name='modal',
            name='body',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='modal',
            name='title',
            field=models.CharField(default='News', max_length=100),
        ),
    ]
