# Generated by Django 3.2.19 on 2023-05-31 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendelapp', '0019_auto_20230531_1713'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Modal',
        ),
    ]
