# Generated by Django 3.2.16 on 2023-06-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendelapp', '0023_auto_20230602_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('about_id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=800)),
            ],
            options={
                'ordering': ['-about_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='modal',
            options={'get_latest_by': 'uploaded_time'},
        ),
        migrations.AlterField(
            model_name='modal',
            name='body',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='modal',
            name='image',
            field=models.ImageField(blank=True, upload_to='notice/'),
        ),
        migrations.AlterField(
            model_name='modal',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
