# Generated by Django 3.2.16 on 2023-06-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendelapp', '0024_auto_20230626_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='about/'),
        ),
    ]
